<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<table style="width: 100%">
<tr>
	<td style="width: 33%"><b>Jméno</b></td>
	<td style="width: 33%"><b>Přihlašovací jméno</b></td>
	<td style="width: 33%"><b>Heslo</b></td>
</tr>
<tr>
	<td>#name</td>
	<td>#login</td>
	<td>#pass_l</td>
</tr>
<tr>
	<td colspan="3">Přihlašte se na adrese: <a href="#path">#path</a></td>
</tr>
</table>
<hr>
</body>
</html>