<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="css/faktura.css" type="text/css" />
</head>
<body>
<p>Střední průmyslová škola Jihlava, tř. Legionářů 3, 586 01 Jihlava</p>
<table>
	<caption>Formulář pro požadavek a příkaz uskutečnění</caption>
	<tbody>
		<tr>
			<td colspan="4" class="left slim">Požadavek (včetně zdůvodnění a předpokádané ceny):</td>
		</tr>
		<tr>
			<td colspan="4">#description</td>
		</tr>
		<tr>
			<td colspan="4" class="slim"><h2>Předběžná kontrola před vznikem závazku</h2></td>
		</tr>
		<tr>
			<td></td>
			<td>Jméno a příjmení</td>
			<td>Datum</td>
			<td>Podpis</td>
		</tr>
		<tr>
			<td class="left"><b>Žadatel:</b></td>
			<td class="left">#zebr_jm</td>
			<td>#zebr_date</td>
			<td></td>
		</tr>
		<tr>
			<td class="left"><b>Věcně schváleno</b></td>
			<td class="left">#confirm_jm</td>
			<td>#confirm_date</td>
			<td></td>
		</tr>
		<tr>
			<td class="left"><b>Příkaz operace:</b></td>
			<td class="left">#reditel_jm</td>
			<td>#reditel_date</td>
			<td></td>
		</tr>
		<tr>
			<td class="left"><b>Správce rozpočtu:</b></td>
			<td class="left">#ucetni_jm</td>
			<td>#ucetni_date</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="4" class="slim"><h2>Předběžná kontrola po vzniku závatku</h2></td>
		</tr>
		<tr>
			<td colspan="4" class="left slim">Příkaz uskuteční plnění podle § 14 vyhlášky č. 416/2004 Sb.</td>
		</tr><!--tady bude ta linka...-->
		<tr>
			<td class="left"><b>Přákaz operace:</b></td>
			<td class="left">#reditel_jm</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="left"><b>Hlavní účetní:</b></td>
			<td class="left">#ucetni_jm</td>
			<td></td>
			<td></td>
		</tr>
		
		
	</tbody>
</table>
</body>
</html>