<section>
	<form method="post" >
		<table>
			<tr height="50px">
				<td>
			<label for="name">Jméno</label>
				</td>
				<td>
			<input type="text" name="name" />
				</td>
			</tr>
			<tr  height="50px">
				<td>
			<label for="pass">Heslo</label>
				</td>
				<td>
			<input type="password" name="pass" />
				</td>
			</tr>
			<tr  height="50px">
				</td>
				<td>
				<td>
			<input type="submit" name="login" value="Log in" />
				</td>
			</tr>
		</table>
	</form>
</section>