			<section id="user_panel">
				<form method="post">
					<table  id="login_l">
						<tr>
							<td>
								<label for="name">Name</label>
							</td>
							<td>
								<label for="pass">Heslo</label>
							</td>
							<td>
							</td>
						</tr>
						<tr>
							<td>
								<input type="text" name="name" id="name" required />
							</td>
							<td>
								<input type="password" name="pass" id="pass" required />
							</td>
							<td>
								<input type="submit" name="login" value="Log in" />
							</td>
						</tr>
					</table>
				</form>
			</section>
